//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduErp.pages.student
{


    public partial class dashboard
    {

        /// <summary>
        /// head control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;

        /// <summary>
        /// ContentPlaceHolder1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;

        /// <summary>
        /// ContentPlaceHolder2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder2;

        /// <summary>
        /// ContentPlaceHolder3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder3;

        /// <summary>
        /// litStudentName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStudentName;

        /// <summary>
        /// litGPA control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litGPA;

        /// <summary>
        /// litCourses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCourses;

        /// <summary>
        /// litAttendance control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAttendance;

        /// <summary>
        /// litFees control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFees;

        /// <summary>
        /// litRecentActivities control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRecentActivities;

        /// <summary>
        /// litUpcomingEvents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUpcomingEvents;

        /// <summary>
        /// litPerfScript control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPerfScript;

        /// <summary>
        /// litCourseScript control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCourseScript;
    }
}
